site_name: Citrix Hypervisor 8.0 CR Software Development Kit Guide
site_description: Citrix Hypervisor 8.0 CR Software Development Kit Guide
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - meta

pages:
- Citrix Hypervisor 8.0 CR Software Development Kit Guide: index.md
- Getting Started: getting-started.md
- Overview: overview.md
- Using: using.md
- Using HTTP: using-http.md
- Citrix Hypervisor Management API Extensions: xs-api-extensions.md
- XenCenter API Extensions: xc-api-extensions.md
