site_name: Citrix Hypervisor 8.0 CR Software Development Kit Guide
site_description: Citrix Hypervisor 8.0 CR Software Development Kit Guide
site_title: Developer Documentation

copyright: 'Copyright &copy; 1999-2019 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

theme:
  name: null
  custom_dir: material
  include_search_page: false
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /media/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png

extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - footnotes
  - meta

nav:
- Citrix Hypervisor 8.0 CR Software Development Kit Guide: index.md
- Getting Started: getting-started.md
- Overview: overview.md
- Using: using.md
- Using HTTP: using-http.md
- Citrix Hypervisor Management API Extensions: xs-api-extensions.md
- XenCenter API Extensions: xc-api-extensions.md
